#docker-compose -p brickshoarder -f "docker-compose.yaml" up -d --build

version: "3.9"

services:
  postgresql:
    image: "ionx/postgres-plv8:12.2"
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: brickshoarder
      NAMEDATALEN: 100
  pgadmin:
    image: "dpage/pgadmin4:latest"
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.pl
      PGADMIN_DEFAULT_PASSWORD: postgres