#docker-compose -p brickshoarder -f "docker-compose.yaml" up -d --build

version: "3.9"

services:
  postgresql:
    image: "ionx/postgres-plv8:12.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: brickshoarder
      NAMEDATALEN: 100
  pgadmin:
    image: "dpage/pgadmin4:latest"
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.pl
      PGADMIN_DEFAULT_PASSWORD: postgres
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - BricksHoarder-data-rabbitmq:/var/lib/rabbitmq
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - BricksHoarder-data-redis:/var/lib/redis/data
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8005:8001"

volumes:
  BricksHoarder-data-rabbitmq:
  BricksHoarder-data-redis:
