#docker-compose -p brickshoarder -f "docker-compose.yaml" up -d --build

version: "3.9"

services:
  pgadmin:
    image: "dpage/pgadmin4:latest"
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.pl
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - BricksHoarder-data-pgadmin:/var/lib/pgadmin
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - BricksHoarder-data-redis:/var/lib/redis/data
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8005:8001"

volumes:
  BricksHoarder-data-redis:
  BricksHoarder-data-pgadmin:
