name: Build and deploy .NET Core application to Function App func-brickshoarder-functions-prd
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/BricksHoarder.Backend/BricksHoarder.Functions/**'
      - '.github/workflows/func-brickshoarder-functions-prd.yml'  
defaults:
  run:
    working-directory: ./src/BricksHoarder.Backend/BricksHoarder.Functions

jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: 'name: Set up QEMU'
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./src/BricksHoarder.Backend
        file: ./Docker/BricksHoarder.Functions/Dockerfile
        push: true
        tags: agolaszewski1337/brickshoarder:latest  