name: func-brickshoarder-timers-prd
permissions:
  id-token: write
  contents: read
on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
    paths:
      - 'src/BricksHoarder.Backend/**'
      - '.github/workflows/func-brickshoarder-timers-prd.yml' 
env:
  AZURE_FUNCTIONAPP_NAME: 'func-as1-brickshoarder-timers-prd'   
  WORKING_DIRECTORY: ./src/BricksHoarder.Backend/BricksHoarder.Functions.Timers
  DOTNET_VERSION: '8.0.x'

defaults:
 run:
  working-directory: ./src/BricksHoarder.Backend/BricksHoarder.Functions.Timers

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prd
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }} # set up AZURE_RBAC_CREDENTIALS secrets in your repository

    - name: Setup DotNet Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output "./published"

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.WORKING_DIRECTORY }}/published
