name: Build and deploy .NET Core application to Function App func-linux-brickshoarder-dev
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/BricksHoarder.Backend/BricksHoarder.Scrappers/**'
      - '.github/workflows/func-linux-brickshoarder-dev.yml' 
env:
  AZURE_FUNCTIONAPP_NAME: 'func-linux-brickshoarder-dev'   
  WORKING_DIRECTORY: ./src/BricksHoarder.Backend/FunctionApp4
  DOTNET_VERSION: '7.0.x'
  PLAYWRIGHT_BROWSERS_PATH: ./published/.playwright/ms-playwright

defaults:
 run:
  working-directory: ./src/BricksHoarder.Backend/BricksHoarder.Scrappers

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    #environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }} # set up AZURE_RBAC_CREDENTIALS secrets in your repository

    - name: Setup DotNet Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output "./published"

    - name: Playwright install
      shell: bash
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        playwright install chromium

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.WORKING_DIRECTORY }}/published
